version: '3'

services:
  chromium-novnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chromium-novnc
    restart: unless-stopped
    environment:
      - VNC_RESOLUTION=1920x1080
      - VNC_DPI=96
      - VNC_PASSWORD=password
      - TZ=Europe/Istanbul
    ports:
      - "5900:5900"  # VNC port
      - "6080:6080"  # noVNC HTTP port
    volumes:
      - /datapool/config/chromium-config:/home/alpine/.config/chromium
    networks:
      - proxy-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy-net:
    external: true
